/**
 * Seed Privacy Policy to Sanity
 * Run with: npx tsx scripts/seed-privacy.ts
 */

import { createClient } from '@sanity/client'
import * as dotenv from 'dotenv'

// Load environment variables
dotenv.config({ path: '.env.local' })

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID!,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || 'production',
  apiVersion: '2024-01-01',
  token: process.env.SANITY_API_TOKEN,
  useCdn: false,
})

function createBlockContent(sections: { style: string; text: string; marks?: string[] }[]) {
  return sections.map((section, index) => ({
    _type: 'block',
    _key: `block-${index}`,
    style: section.style,
    children: [
      {
        _type: 'span',
        _key: `span-${index}`,
        text: section.text,
        marks: section.marks || [],
      },
    ],
    markDefs: [],
  }))
}

async function seedPrivacy() {
  console.log('🚀 Seeding Privacy Policy...')

  const content = createBlockContent([
    { style: 'h1', text: 'The WordPress Team - Privacy Policy' },
    { style: 'normal', text: 'Effective date: December 5, 2024', marks: ['strong'] },
    { style: 'normal', text: '' },
    { style: 'h2', text: '1. Introduction' },
    { style: 'normal', text: 'Welcome to The WordPress Team' },
    { style: 'normal', text: 'The WordPress Team ("us", "we", or "our") operates https://thewordpressteam.co.za (hereinafter referred to as "Service").' },
    { style: 'normal', text: 'Our Privacy Policy governs your visit to https://thewordpressteam.co.za, and explains how we collect, safeguard and disclose information that results from your use of our Service.' },
    { style: 'normal', text: 'We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '2. Definitions' },
    { style: 'normal', text: 'SERVICE means the https://thewordpressteam.co.za website operated by The WordPress Team.' },
    { style: 'normal', text: 'PERSONAL DATA means data about a living individual who can be identified from those data.' },
    { style: 'normal', text: 'USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself.' },
    { style: 'normal', text: 'COOKIES are small files stored on your device (computer or mobile device).' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '3. Information Collection and Use' },
    { style: 'normal', text: 'We collect several different types of information for various purposes to provide and improve our Service to you.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '4. Types of Data Collected' },
    { style: 'normal', text: 'Personal Data: While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you, including:' },
    { style: 'normal', text: '• Email address' },
    { style: 'normal', text: '• First name and last name' },
    { style: 'normal', text: '• Phone number' },
    { style: 'normal', text: '• Website URL' },
    { style: 'normal', text: '• Cookies and Usage Data' },
    { style: 'normal', text: '' },
    { style: 'normal', text: 'Usage Data: We may also collect information that your browser sends whenever you visit our Service, including your computer\'s IP address, browser type, browser version, the pages of our Service that you visit, the time and date of your visit, and other diagnostic data.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '5. Use of Data' },
    { style: 'normal', text: 'The WordPress Team uses the collected data for various purposes:' },
    { style: 'normal', text: '• To provide and maintain our Service' },
    { style: 'normal', text: '• To notify you about changes to our Service' },
    { style: 'normal', text: '• To provide customer support' },
    { style: 'normal', text: '• To gather analysis to improve our Service' },
    { style: 'normal', text: '• To monitor the usage of our Service' },
    { style: 'normal', text: '• To detect, prevent and address technical issues' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '6. Retention of Data' },
    { style: 'normal', text: 'We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '7. Transfer of Data' },
    { style: 'normal', text: 'Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.' },
    { style: 'normal', text: 'The WordPress Team will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '8. Disclosure of Data' },
    { style: 'normal', text: 'We may disclose personal information that we collect, or you provide:' },
    { style: 'normal', text: '• Disclosure for Law Enforcement: Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law.' },
    { style: 'normal', text: '• Business Transaction: If we are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '9. Security of Data' },
    { style: 'normal', text: 'The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '10. Your Data Protection Rights Under GDPR' },
    { style: 'normal', text: 'If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights:' },
    { style: 'normal', text: '• The right to access, update or delete the information we have on you' },
    { style: 'normal', text: '• The right of rectification' },
    { style: 'normal', text: '• The right to object' },
    { style: 'normal', text: '• The right of restriction' },
    { style: 'normal', text: '• The right to data portability' },
    { style: 'normal', text: '• The right to withdraw consent' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '11. Your Rights Under POPIA (South Africa)' },
    { style: 'normal', text: 'If you are a South African resident, you have rights under the Protection of Personal Information Act (POPIA):' },
    { style: 'normal', text: '• The right to be notified when personal information is collected' },
    { style: 'normal', text: '• The right to access your personal information' },
    { style: 'normal', text: '• The right to request correction of your personal information' },
    { style: 'normal', text: '• The right to request deletion of your personal information' },
    { style: 'normal', text: '• The right to object to processing of your personal information' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '12. Service Providers' },
    { style: 'normal', text: 'We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.' },
    { style: 'normal', text: 'These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '13. Analytics' },
    { style: 'normal', text: 'We may use third-party Service Providers to monitor and analyze the use of our Service, including Google Analytics.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '14. Payments' },
    { style: 'normal', text: 'We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. Stripe).' },
    { style: 'normal', text: 'We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '15. Links to Other Sites' },
    { style: 'normal', text: 'Our Service may contain links to other sites that are not operated by us. We strongly advise you to review the Privacy Policy of every site you visit.' },
    { style: 'normal', text: 'We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '16. Children\'s Privacy' },
    { style: 'normal', text: 'Our Services are not intended for use by children under the age of 18 ("Children"). We do not knowingly collect personally identifiable information from Children under 18.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '17. Changes to This Privacy Policy' },
    { style: 'normal', text: 'We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.' },
    { style: 'normal', text: 'You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '18. Contact Us' },
    { style: 'normal', text: 'If you have any questions about this Privacy Policy, please contact us:' },
    { style: 'normal', text: 'By email: emmanuel@thewordpressteam.co.za' },
  ])

  try {
    await client.createOrReplace({
      _id: 'privacyPolicy',
      _type: 'privacyPolicy',
      title: 'Privacy Policy',
      effectiveDate: '2024-12-05',
      content,
    })
    console.log('✅ Privacy Policy seeded successfully!')
  } catch (error) {
    console.error('❌ Error seeding Privacy Policy:', error)
  }
}

seedPrivacy()
