/**
 * Seed Terms & Conditions to Sanity
 * Run with: npx tsx scripts/seed-terms.ts
 */

import { createClient } from '@sanity/client'
import * as dotenv from 'dotenv'

// Load environment variables
dotenv.config({ path: '.env.local' })

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID!,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || 'production',
  apiVersion: '2024-01-01',
  token: process.env.SANITY_API_TOKEN,
  useCdn: false,
})

// Convert markdown-style content to Sanity block content
function createBlockContent(sections: { style: string; text: string; marks?: string[] }[]) {
  return sections.map((section, index) => ({
    _type: 'block',
    _key: `block-${index}`,
    style: section.style,
    children: [
      {
        _type: 'span',
        _key: `span-${index}`,
        text: section.text,
        marks: section.marks || [],
      },
    ],
    markDefs: [],
  }))
}

async function seedTerms() {
  console.log('🚀 Seeding Terms & Conditions...')

  const content = createBlockContent([
    { style: 'h1', text: 'The WordPress Team - Terms & Conditions' },
    { style: 'normal', text: 'Last updated: December 5, 2024', marks: ['strong'] },
    { style: 'normal', text: '' },
    { style: 'normal', text: 'THIS TERMS OF SERVICE AGREEMENT (the "Agreement") constitutes a legally binding agreement by and between THE WORDPRESS TEAM, a business operating in South Africa ("The WordPress Team," "we," "us," or "our") and the client, whether personally or on behalf of an entity ("Client," "you," or "your"), with regard to access and use of The WordPress Team\'s website: https://thewordpressteam.co.za/ (the "Website") and any WordPress maintenance services provided thereunder (the "Services"). Failure to agree and adhere to all of the terms, conditions and obligations contained herein results in the express prohibition of the Client\'s use of the Website and Services, and the Client is ordered to discontinue use immediately.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '1. Service Description' },
    { style: 'normal', text: 'The WordPress Team provides comprehensive WordPress maintenance services including but not limited to:' },
    { style: 'normal', text: '• Security monitoring and malware scanning' },
    { style: 'normal', text: '• Automated backup and restoration services' },
    { style: 'normal', text: '• Performance optimization' },
    { style: 'normal', text: '• WordPress core, plugin, and theme updates' },
    { style: 'normal', text: '• 24/7 uptime monitoring' },
    { style: 'normal', text: '• SEO health monitoring' },
    { style: 'normal', text: '• Technical support and troubleshooting' },
    { style: 'normal', text: '• Database optimization' },
    { style: 'normal', text: '• Emergency site recovery' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '2. Intellectual Property Rights' },
    { style: 'normal', text: 'Unless otherwise indicated, the Website is the property of The WordPress Team and all source code, databases, functionality, software, website designs, audio, video, text, photographs and graphics of any nature and regardless of format (herein, collectively or individually, the "Content") and the trademarks, service marks, and logos contained therein (the "Marks") are owned and controlled by The WordPress Team and are protected by copyright and trademark laws.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '3. Client Website Ownership' },
    { style: 'normal', text: 'Client retains full ownership of their WordPress website, including all content, data, databases, and materials. The WordPress Team provides maintenance services only and does not claim any ownership interest in Client\'s website or its content.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '4. Access and Credentials' },
    { style: 'normal', text: 'To provide the Services, Client must provide The WordPress Team with administrative access to their WordPress website, hosting account, and related services as necessary. Client warrants that they have the legal authority to grant such access.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '5. Client Responsibilities' },
    { style: 'normal', text: 'Client agrees to maintain independent backups, respond to requests in a timely manner, ensure website content complies with all applicable laws, and maintain active accounts with hosting providers.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '6. Service Limitations and Exclusions' },
    { style: 'normal', text: 'The Services DO NOT include: Major website redesigns, custom plugin/theme development, content creation, SEO content strategy, social media management, email marketing, paid advertising management, or hosting services.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '7. Subscription and Payment Terms' },
    { style: 'normal', text: 'Services are billed monthly or annually in advance. Subscriptions automatically renew unless cancelled. Late payments may result in service suspension.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '8. Refund Policy' },
    { style: 'normal', text: 'Client may request a 75% refund within the first 7 days of their initial subscription. No refunds will be provided after the trial period.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '9. Pause and Cancellation' },
    { style: 'normal', text: 'Client may pause or cancel their subscription at any time. Upon cancellation, Services continue until the end of the current paid billing period.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '10. Service Level Agreement (SLA)' },
    { style: 'normal', text: 'We monitor Client websites every 60 seconds. Standard support requests have a 48-hour response time. Urgent issues have a 2-4 hour response during business hours.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '11. Backup and Data Protection' },
    { style: 'normal', text: 'We perform automated daily backups stored in secure offsite cloud storage with a 30-day retention period.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '12. Security Services' },
    { style: 'normal', text: 'Daily malware and vulnerability scanning, real-time threat monitoring, firewall configuration, and security hardening implementation are included.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '13. Performance Optimization' },
    { style: 'normal', text: 'Services include image compression, caching configuration, database optimization, code minification, and CDN setup.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '14. WordPress Updates' },
    { style: 'normal', text: 'WordPress core updates are applied within 48 hours of release for security updates. Plugin and theme updates are tested before applying to live sites.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '15. Third-Party Services and Integrations' },
    { style: 'normal', text: 'Client remains responsible for their hosting, domain registration, email services, and other third-party accounts.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '16. White Label Services' },
    { style: 'normal', text: 'All reports and client-facing communications can be white-labeled with Client\'s branding at no additional cost.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '17. Limitation of Liability' },
    { style: 'normal', text: 'TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE WORDPRESS TEAM SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '18. Indemnification' },
    { style: 'normal', text: 'Client agrees to defend, indemnify, and hold harmless The WordPress Team from any claims arising from Client\'s use of the Services.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '19. Warranties and Disclaimers' },
    { style: 'normal', text: 'THE SERVICES ARE PROVIDED ON AN "AS-IS" AND "AS-AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '20. Intellectual Property and Licensing' },
    { style: 'normal', text: 'Client retains all rights to their content. Client is responsible for obtaining proper licenses for all materials used on their website.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '21. Confidentiality' },
    { style: 'normal', text: 'Both parties agree to maintain confidentiality of any proprietary information shared during the course of providing Services.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '22. Testimonials and Portfolio Use' },
    { style: 'normal', text: 'Unless Client explicitly opts out, The WordPress Team reserves the right to display Client\'s website in our portfolio and marketing materials.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '23. Non-Disclosure Agreements (NDA)' },
    { style: 'normal', text: 'Client may request a mutual NDA if confidentiality of their project is required.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '24. Communication and Notices' },
    { style: 'normal', text: 'All official communications should be sent to: emmanuel@thewordpressteam.co.za' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '25. User Representations' },
    { style: 'normal', text: 'By using the Services, Client represents they have legal capacity to agree to these Terms and will not use the Services for illegal purposes.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '26. Prohibited Activities' },
    { style: 'normal', text: 'Client agrees not to use the Services for illegal content, malware distribution, or any activities that violate applicable laws.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '27. Privacy and Data Protection' },
    { style: 'normal', text: 'We implement industry-standard security measures to protect Client data including encryption and access controls.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '28. International Clients and Governing Law' },
    { style: 'normal', text: 'These Terms shall be governed by the laws of the Republic of South Africa.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '29. Dispute Resolution' },
    { style: 'normal', text: 'Parties agree to attempt informal resolution before pursuing litigation.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '30. Changes to Terms of Service' },
    { style: 'normal', text: 'The WordPress Team reserves the right to modify these Terms with 30 days advance notice.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '31. Service Modifications' },
    { style: 'normal', text: 'The WordPress Team reserves the right to modify or discontinue any aspect of the Services.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '32. Force Majeure' },
    { style: 'normal', text: 'The WordPress Team shall not be liable for failures due to causes beyond reasonable control.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '33. Assignment and Transfer' },
    { style: 'normal', text: 'Client may not assign these Terms without prior written consent.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '34. Severability' },
    { style: 'normal', text: 'If any provision is found unenforceable, the remaining provisions remain in full force.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '35. Entire Agreement' },
    { style: 'normal', text: 'These Terms constitute the entire agreement between Client and The WordPress Team.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '36. Waiver' },
    { style: 'normal', text: 'Failure to enforce any provision shall not constitute a waiver.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '37. Relationship of Parties' },
    { style: 'normal', text: 'Client and The WordPress Team are independent contractors.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '38. Survival' },
    { style: 'normal', text: 'Certain provisions survive termination including Limitation of Liability, Indemnification, and Confidentiality.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '39. Electronic Communications' },
    { style: 'normal', text: 'Client consents to receive communications electronically.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '40. Miscellaneous Provisions' },
    { style: 'normal', text: 'These Terms are provided in English. All time periods are calendar days unless specified.' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '41. Contact Information' },
    { style: 'normal', text: 'The WordPress Team' },
    { style: 'normal', text: 'Email: emmanuel@thewordpressteam.co.za' },
    { style: 'normal', text: 'Business Hours: Monday - Friday, 9:00 AM - 5:00 PM (SAST)' },
    { style: 'normal', text: '' },
    { style: 'h2', text: '42. Acknowledgment' },
    { style: 'normal', text: 'BY SUBSCRIBING TO THE SERVICES, CLIENT ACKNOWLEDGES THAT THEY HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS OF SERVICE.' },
    { style: 'normal', text: '' },
    { style: 'normal', text: 'Version: 1.0', marks: ['strong'] },
  ])

  try {
    await client.createOrReplace({
      _id: 'termsAndConditions',
      _type: 'termsAndConditions',
      title: 'Terms & Conditions',
      lastUpdated: '2024-12-05',
      version: '1.0',
      content,
    })
    console.log('✅ Terms & Conditions seeded successfully!')
  } catch (error) {
    console.error('❌ Error seeding Terms & Conditions:', error)
  }
}

seedTerms()
