import { defineType, defineField } from 'sanity'
import { StarIcon } from '@sanity/icons'

export default defineType({
  name: 'benefit',
  title: 'Benefit',
  type: 'document',
  icon: StarIcon,
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      rows: 2,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'emoji',
      title: 'Icon Emoji',
      type: 'string',
      description: 'Select an emoji icon',
      options: {
        list: [
          // Security & Protection
          { title: '🛡️ Shield', value: '🛡️' },
          { title: '🔒 Lock', value: '🔒' },
          { title: '🔐 Locked Key', value: '🔐' },
          { title: '🔑 Key', value: '🔑' },
          { title: '🚨 Alert', value: '🚨' },
          { title: '✅ Checkmark', value: '✅' },
          // Performance & Speed
          { title: '⚡ Lightning', value: '⚡' },
          { title: '🚀 Rocket', value: '🚀' },
          { title: '💨 Speed', value: '💨' },
          { title: '🏎️ Race Car', value: '🏎️' },
          { title: '⏱️ Stopwatch', value: '⏱️' },
          // Cloud & Backup
          { title: '☁️ Cloud', value: '☁️' },
          { title: '💾 Save/Backup', value: '💾' },
          { title: '🗄️ Database', value: '🗄️' },
          { title: '📦 Package', value: '📦' },
          // Updates & Maintenance
          { title: '🔄 Refresh', value: '🔄' },
          { title: '🔧 Wrench', value: '🔧' },
          { title: '⚙️ Settings', value: '⚙️' },
          { title: '🛠️ Tools', value: '🛠️' },
          { title: '🔨 Hammer', value: '🔨' },
          // Quality & Excellence
          { title: '⭐ Star', value: '⭐' },
          { title: '🌟 Glowing Star', value: '🌟' },
          { title: '✨ Sparkles', value: '✨' },
          { title: '🏆 Trophy', value: '🏆' },
          { title: '🎯 Target', value: '🎯' },
          { title: '💎 Diamond', value: '💎' },
          { title: '👑 Crown', value: '👑' },
          // Communication & Support
          { title: '🎧 Headphones', value: '🎧' },
          { title: '💬 Chat', value: '💬' },
          { title: '📧 Email', value: '📧' },
          { title: '📞 Phone', value: '📞' },
          { title: '🤝 Handshake', value: '🤝' },
          // Business & Growth
          { title: '📈 Growth', value: '📈' },
          { title: '💰 Money Bag', value: '💰' },
          { title: '💵 Dollar', value: '💵' },
          { title: '💳 Credit Card', value: '💳' },
          { title: '🎁 Gift', value: '🎁' },
          // Flexibility & Scaling
          { title: '🔀 Flexible', value: '🔀' },
          { title: '📊 Chart', value: '📊' },
          { title: '🧩 Puzzle', value: '🧩' },
          { title: '🎨 Palette', value: '🎨' },
          // Time & Schedule
          { title: '⏰ Clock', value: '⏰' },
          { title: '📅 Calendar', value: '📅' },
          { title: '⏳ Hourglass', value: '⏳' },
          { title: '🕐 Time', value: '🕐' },
          // Tech & WordPress
          { title: '💻 Laptop', value: '💻' },
          { title: '🖥️ Desktop', value: '🖥️' },
          { title: '🌐 Globe', value: '🌐' },
          { title: '📱 Mobile', value: '📱' },
          { title: '🔌 Plugin', value: '🔌' },
          // Positive & General
          { title: '❤️ Heart', value: '❤️' },
          { title: '👍 Thumbs Up', value: '👍' },
          { title: '🙌 Celebration', value: '🙌' },
          { title: '💪 Strong', value: '💪' },
          { title: '🎉 Party', value: '🎉' },
          { title: '😊 Happy', value: '😊' },
          { title: '🤩 Excited', value: '🤩' },
          { title: '👀 Eyes', value: '👀' },
          { title: '🔥 Fire', value: '🔥' },
          { title: '💯 100', value: '💯' },
        ],
        layout: 'dropdown',
      },
      initialValue: '⭐',
    }),
    defineField({
      name: 'icon',
      title: 'Custom Icon Image (Optional)',
      type: 'image',
      options: { hotspot: true },
      description: 'Upload a custom icon image. If set, this overrides the dropdown selection.',
    }),
    defineField({
      name: 'background',
      title: 'Background Style',
      type: 'string',
      description: 'Select a background gradient/image style',
      options: {
        list: [
          { title: 'Style 1 - Orange/Red Gradient', value: '1' },
          { title: 'Style 2 - Purple/Pink Gradient', value: '2' },
          { title: 'Style 3 - Blue Gradient', value: '3' },
          { title: 'Style 4 - Green Gradient', value: '4' },
          { title: 'Style 5 - Yellow/Orange Gradient', value: '5' },
          { title: 'Style 6 - Teal Gradient', value: '6' },
          { title: 'Style 7 - Red Gradient', value: '7' },
          { title: 'Style 8 - Dark Purple Gradient', value: '8' },
          { title: 'Style 9 - Coral Gradient', value: '9' },
          { title: 'Style 10 - Cyan Gradient', value: '10' },
        ],
        layout: 'dropdown',
      },
      initialValue: '1',
    }),
    defineField({
      name: 'colorScheme',
      title: 'Color Scheme (Legacy)',
      type: 'string',
      hidden: true,
      options: {
        list: [
          { title: 'Red (Brand)', value: 'red' },
          { title: 'Orange', value: 'orange' },
          { title: 'Purple', value: 'purple' },
          { title: 'Blue', value: 'blue' },
          { title: 'Yellow', value: 'yellow' },
          { title: 'Green', value: 'green' },
          { title: 'Pink', value: 'pink' },
        ],
        layout: 'dropdown',
      },
      initialValue: 'red',
    }),
    defineField({
      name: 'order',
      title: 'Display Order',
      type: 'number',
      initialValue: 0,
    }),
  ],
  orderings: [
    {
      title: 'Display Order',
      name: 'orderAsc',
      by: [{ field: 'order', direction: 'asc' }],
    },
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'description',
      media: 'icon',
    },
  },
})
